### PR TITLE
Org agenda mode // Revive zz, zt, and zb. Revive H, M, and L with `g` prefix.

### PR DESCRIPTION
**Pull request by crocket**
Those movement keys from vim are useful.

### CODE REVIEW

**Comment by crocket** [comment]
This fixes https://github.com/Somelauw/evil-org-mode/issues/69 and https://github.com/Somelauw/evil-org-mode/issues/65

**Comment by Somelauw** [comment]
@Ambrevar Looks mostly good to me. Will merge soon, unless you have objections.

**Comment by Ambrevar** [comment]
Maybe I missed part of the discussion, but what about binding `org-agenda-view-mode-dispatch` to something other than `z`?

**Comment by crocket** [comment]
Like `Z`?

**Comment by Ambrevar** [comment]
Looks good to me!

**Comment by crocket** [comment]
I think it's a good idea to map `org-agenda-view-mode-dispatch` to `gD` because `org-agenda-goto-date` is mapped to `gd`.

**Comment by Somelauw** [comment]
Personally, I do like having `ZZ` and `ZQ` everywhere

**Comment by crocket** [comment]
I revised the pull request.

**Comment by Ambrevar** [comment]
Looks good to me!

**Comment by crocket** [comment]
If it looks good, can you merge soon?

**Comment by Ambrevar** [comment]
@Somelauw Friendly ping ;)

**Comment by Somelauw** [comment]
I'll see if I can look at this later today.

**Pull request merged**
