### PR TITLE
Add calendar key theme

### PR DESCRIPTION
**Pull request by Ambrevar**
At last, get rid of those arrow-based bindings...

### CODE REVIEW

**Comment by Somelauw** [comment]
Thanks. I'll need some time to test it, but I'll probably merge it over the weekend.

**Comment by Somelauw** [comment]
I've tried it, but it doesn't seem to work for me. How exactly have you set up evil that you are in insert mode in org-read-date-minibuffer-map?
It does work if I use with (define-key ...) instead of (evil-define-key 'insert ...)

**Comment by Somelauw** [comment]
By the way, should `C-b` and `C-f` be bound? In minibuffers these keys usually go forward/backward chars.

**Comment by Ambrevar** [comment]
Correct, my change only works if you enable Evil in the minibuffer, which is not the default (sorry I forgot to mention that).  Here is how I use Evil in the minibuffer:

```
(dolist
    (keymap
     ;; https://www.gnu.org/software/emacs/manual/html_node/elisp/
     ;; Text-from-Minibuffer.html#Definition of minibuffer-local-map
     '(minibuffer-local-map
       minibuffer-local-ns-map
       minibuffer-local-completion-map
       minibuffer-local-must-match-map
       minibuffer-local-isearch-map))
  (evil-define-key 'normal (eval keymap) (kbd "<escape>") 'abort-recursive-edit)
  (evil-define-key 'normal (eval keymap) (kbd "<return>") 'exit-minibuffer))

(defun evil-minibuffer-setup ()
  (set (make-local-variable 'evil-echo-state) nil)
  ;; (evil-set-initial-state 'mode 'insert) is the evil-proper
  ;; way to do this, but the minibuffer doesn't have a mode.
  ;; The alternative is to create a minibuffer mode (here), but
  ;; then it may conflict with other packages' if they do the same.
  (evil-insert 1))
(add-hook 'minibuffer-setup-hook 'evil-minibuffer-setup)
;;; Because of the above minibuffer-setup-hook, some bindings need be reset.
(evil-define-key 'normal evil-ex-completion-map (kbd "<escape>") 'abort-recursive-edit)
```

- If we use `define-key` instead of `evil-define-key`, we lose the ability to switch back to Emacs mode.
Which is arguably not so useful.  It's also less consistent.

- If we use `evil-define-key`, we should provide the user with the above code or similar to enable Evil in the minibffer.  Or maybe just in `org-read-date-minibuffer-local-map`.


Generally speaking, I think it makes sense to use Evil bindings in the minibuffer too: we are editing text there after all.  Conversely, using Emacs bindings there imposes a recurring context switch on the user.
It does not seem very natural to have a different meaning for `C-f`/`C-b` just in one spot of Emacs+Evil.
With Emacs bindings, `C-v`/`M-v` are bound the way I did for `C-f`/`C-b` in my patch.

Last but not least, it always frustrates me that I simply cannot browse the calendar without reaching for the arrow keys...

**Comment by Somelauw** [comment]
>    If we use evil-define-key, we should provide the user with the above code or similar to enable Evil in the minibffer. Or maybe just in org-read-date-minibuffer-local-map.

I think plug-and-plug (using `define-key`) would be preferable in this case, because evilifying your minibuffer is more of a hassle, may not be desirable and should probably be left as a choice to the user. I don't think the `M-hjkl` keys do much import in minibuffers in Emacs state anyway. It's a bit unfortunate that this is the only keytheme that doesn't populate `evil-org-mode-map`, but I think it might be overkill to create a separate minor mode for this. I'm open to cleaner solutions, though.

> It does not seem very natural to have a different meaning for C-f/C-b just in one spot of Emacs+Evil.
With Emacs bindings, C-v/M-v are bound the way I did for C-f/C-b in my patch.

You could bind them in that case. Personally, I'm already used to having readline bindings (`C-f`, `M-b` which don't exist in Vim) work in every Emacs minibuffer, so I'll add an option to disable these for me and other programmers used to readline.

**Comment by Ambrevar** [comment]
I've commited the change using `define-key` instead.  Let me know.

**Comment by Ambrevar** [comment]
Any thought?

**Comment by Somelauw** [comment]
Thanks, your commit has been merged.

I've made the bindings use `evil-org-movement-bindings` which makes them slightly more convenient for non-qwerty people. I've also added some documentation and enabled your bindings by default.

**Pull request closed without merging**
