### PR TITLE
org-agenda: Init

### PR DESCRIPTION
**Pull request by Ambrevar**

### CODE REVIEW

**Comment by Ambrevar** [comment]
Do no merge yet.

Fixes issue #15.  I've taken @Somelauw suggestions into account regarding the mark keys.

A few questions remain:
- For now I chose `f` for filtering.  What's the idiomatic binding in Vim for filtering?  Or in other Evil modes?

- Same question for "limiting" (is it different from filtering?), which is now bound to `~`.

- 3 original bindings are not bound yet as I'm not sure of their use:
        'org-agenda-date-prompt
        'org-agenda-show-the-flagging-note
        'org-save-all-org-buffers

- We need to add the new function to the package documentation.  Or is this going to be a different package?

**Comment by Somelauw** [comment]
Thank your for this pull request.

> I've taken @Somelauw suggestions into account regarding the mark keys.

I suggest the following:
```emacs-lisp
  "m" 'org-agenda-bulk-toggle           ; M-m (m, u)
  "M" 'org-agenda-bulk-toggle-all       ; M-*
  "*" 'org-agenda-bulk-mark-all         ; *
  "U" 'org-agenda-bulk-remove-all-marks ; U
  "%" 'org-agenda-bulk-mark-regexp      ; %
```

For `org-redo-all` I advise `gR`, because it's related to `org-redo`.

>    For now I chose f for filtering. What's the idiomatic binding in Vim for filtering? Or in other Evil modes? Same question for "limiting" (is it different from filtering?), which is now bound to ~

These look good to me. You can put limiting on some key under `f` if you want, but `~` is also fine.

>    3 original bindings are not bound yet as I'm not sure of their use:
>
>      'org-agenda-date-prompt
>      'org-agenda-show-the-flagging-note
>      'org-save-all-org-buffers

`org-save-all-org-buffers` does what it's name says. It's already bound to `C-x C-s`.
Maybe it can be called on `:w`. For the others, we need to find out if we need them and what to bind them to.

> We need to add the new function to the package documentation. Or is this going to be a different package?

For now, either on [doc/evil-org-agenda.org] or in one of the existing documents. I think one nice thing to include in the documentation would be a side by side comparison of the Emacs and the evil keys.

With regards to different package or not, after this PR is merged, I'll probably ask the guys on melpa what they think is best.

**Comment by Ambrevar** [comment]
For the marks: we don't need `toggle-all + mark-all + unmark-all`, `toggle-all` and one of the two is enough.
In my current configuration:

- If no mark has been set, `*` will mark all.
- If some marks habe been set, `M*` will mark all.

It might be lighter on the cognitive load, what do you think?

> Maybe it can be called on :w. For the others, we need to find out if we need them and what to bind them to.

I have no clue how to do this.  You?

**Comment by Ambrevar** [comment]
`U` for  `org-agenda-bulk-remove-all-marks` could be confused with `u` (`org-agenda-undo`).

**Comment by Ambrevar** [comment]
> I think one nice thing to include in the documentation would be a side by side comparison of the Emacs and the evil keys.

There is no such thing for evil-org, right?
I'll make a simple list of bindings for now, let me know what you think.

**Comment by Ambrevar** [comment]
Please don't merge now: I don't think that `f` for filtering is a good idea.  "Filtering" should be quite a ubiquitous concept that we are going to find in many other modes, some of them which may not like that we rebind `f`.  I'll think this through and hopefully come up with something more adequate.

**Comment by Ambrevar** [comment]
I've workout quite some binding sets for many of vanilla-Emacs special modes:
https://github.com/Ambrevar/evil-special-modes.

Some conclusions:

- `s` is generally used for searching / filtering.  So I've replaced the `f`-prefixed bindings here by `s`.

- `~` is a nice toggle key as it already toggles case in Vim, so I use it to toggle all marks.  `*` is more meaningful to "mark all".

I think we are almost good to go.
Let me know what you think.

**Comment by Somelauw** [comment]
You are now using `z` for set-commands, but you are also using z as your view-dispatch key.
Do these keys conflict?

> There is no such thing for evil-org, right?
> I'll make a simple list of bindings for now, let me know what you think.

I don't think evil-org needs it, because its bindings are mostly complementary and easily derived from the original. For evil-org-agenda it can be helpful, because some users only know commands by key.

> In my current configuration:
>
>    If no mark has been set, * will mark all.
>    If some marks habe been set, M* will mark all.

I think that if you are going to bind `*` or `U` for marking, it's less confusing if they have the same function as in Emacs mode or extend the original Emacs function. But you have already changed this to `~`. Is this key available on all (most) keyboard layouts?

> +    "H" 'evil-org-agenda-previous-todo-keyword
> +    "L" 'evil-org-agenda-next-todo-keyword

Where are these functions defined?

**Comment by Ambrevar** [comment]
> You are now using z for set-commands, but you are also using z as your view-dispatch key.
> Do these keys conflict?

Yes they do, sorry, I slipped there.  I'll change that prefix to something else.  Any suggestion?

I'll complete the table with Emacs bindings.

> I think that if you are going to bind * or U for marking, it's less confusing if they have the same function as in Emacs mode or extend the original Emacs function.

I think we should not use `U` or `u` for marking as it's used in too many modes for other things, mostly "undoing".
I think `*` is good for "mark all", which is what Emacs does with org-agenda.

Never the less, in the current state there is no consistent binding for mark (see Dired), so if we want to enforce some consistency, we've got to make some decisions that cannot fit all Emacs default bindings.

> But you have already changed this to ~. Is this key available on all (most) keyboard layouts?

It's an ASCII key and among the dozen keyboard layouts I've tried in my life, it was always there.

> "H" 'evil-org-agenda-previous-todo-keyword
> "L" 'evil-org-agenda-next-todo-keyword
> Where are these functions defined?

Some spurious left-over, I'll fix that.

If you've got time to have a look at https://github.com/Ambrevar/evil-special-modes, that could help the discussion around org-agenda as well.  I think I'm going to publish those bindings soon.

**Comment by Ambrevar** [comment]
I've used "pe", "pt" and "o" for the org-*-set-* keys as "p" and "o" were the only lowercase letters that were still free.  Bonus: they are next to each other on QWERTY.

**Comment by Somelauw** [comment]
> If you've got time to have a look at https://github.com/Ambrevar/evil-special-modes, that could help the > discussion around org-agenda as well. I think I'm going to publish those bindings soon.

Cool, I think it would help to create issues in the repositories of the packages that you mention to get more people involved with your project.

> I think we should not use U or u for marking as it's used in too many modes for other things, mostly "undoing".

Well, `U` can mean "undo marking" in this context. Which modes bind this key to other things (related to undo) except evil-normal-state by the way?

> I've used "pe", "pt" and "o" for the org--set- keys as "p" and "o" were the only lowercase letters that were still free. Bonus: they are next to each other on QWERTY.

How about putting these on `c`? `ce` can be a mnemonic for "change effort". `c` is already used for clocks, but I think there is room for both. What does `p` stand for? Leaving `p` and `o` free would also help create future bindings.

**Comment by Ambrevar** [comment]
> Cool, I think it would help to create issues in the repositories of the packages that you mention to get more people involved with your project.

Which packages that I mention?

`evil-special-modes` contains bindings only for the _vanilla_ special modes, non of them is a third-party package.

To get people involved, we need people to file issues and send pull requests on `evil-special-modes`.
I'll polish it a little bit and publish it in the coming days.

> Well, U can mean "undo marking" in this context. Which modes bind this key to other things (related to undo) except evil-normal-state by the way?

Not sure I understood your question, but those are some default uses for "u" and "U" in Emacs (without Evil):

- In Info-mode, "u" is bound to "up".
- In package-menu-mode, "U" upgrades all packages.
- In man-mode, "u" updates the buffer (i.e. reloads it).
- In customize, "u" goes to parent, "U" call `Custom-no-edit`.

"Undo marking" is semantically bound to marking, not "undoing things" in my opinion.
Else all kinds of reverse actions could be called "undoing", e.g. `b` (`evil-backward-word-begin`) could be the undoing of `w`.  I'm stretching it a little, I know, but I hope you get what I mean.

> How about putting these on c? ce can be a mnemonic for "change effort". c is already used for clocks, but I think there is room for both. What does p stand for? Leaving p and o free would also help create future bindings.

Why not?  I think it's a good idea.  The main downside is that `c` will be a prefix for two different things, which is arguably bad practice.
Vim already does that for "g" and "z" anyways.

If you confirm you think it's a better idea, then I'll commit that change.

**Comment by Ambrevar** [comment]
I just had another idea for the marks: if we use `m`, then `'` is free, so why not use it?
The original meaning of `'` is "go to mark", so I suggest we turn it to "execute action on mark", that is the current command of `x`.

**Comment by Somelauw** [comment]
> Which packages that I mention?

Maybe we can get some of the maintainers of the packages below "Third-party packages" involved in the discussion towards more consistency between evil-packages.

> Why not? I think it's a good idea. The main downside is that c will be a prefix for two different things, which is arguably bad practice.
Vim already does that for "g" and "z" anyways.
>
> If you confirm you think it's a better idea, then I'll commit that change

Maybe slightly bad practice, but there are not that many clock commands. The commands for `org-clock-in` and `org-clock-out` aren't on `c` either. Otherwise, the clock commands can go on `C` or we should have a convention that `c` followed by lowercase "sets" something and `c` followed by an uppercase is a clock command, but that's less friendly to one's fingers.

> I just had another idea for the marks: if we use m, then ' is free, so why not use it?
The original meaning of ' is "go to mark", so I suggest we turn it to "execute action on mark", that is the current command of x.

Well, not completely because `m` marks the current buffer (org-agenda), which I think is not useful, but `'` can jump from org-agenda to a location in a different (normal) buffer, which might be useful to someone? Then again, I rarely use marks myself so I don't really mind rebinding this.

> M-h, M-l for org-agenda-todo-previousset, org-agenda-todo-nextset

I don't know about these. If `M-h` and `M-l` switch between keywords in org-agenda, people may think they also work in regular evil-org-mode, but there they are used for promotion / demotion of headings. It's not consistent.

Actually, I find it strange that there is an `org-agenda-todo-previousset` but no `org-agenda-todo-previous-keyword` function. Regular evil-org-mode binds `org-agenda-todo-previousset`, `org-agenda-todo-nextset` commands to `C-S-h`, `C-S-l` by the way and the other ones to just `H` and `L`.

By the way, I think we are close to finishing.

**Comment by Ambrevar** [comment]
> Well, not completely because m marks the current buffer (org-agenda), which I think is not useful, but ' can jump from org-agenda to a location in a different (normal) buffer, which might be useful to someone? 

Good point.

> Actually, I find it strange that there is an org-agenda-todo-previousset but no org-agenda-todo-previous-keyword function.

Agreed.  Unless we are missing something, this should probably be reported upstream.

> Regular evil-org-mode binds org-agenda-todo-previousset, org-agenda-todo-nextset commands to C-S-h, C-S-l by the way and the other ones to just H and L.

`M-l` and `M-h` are unused in Emacs mode and free in Evil mode, so why not just use them if we already use `M-j` and `M-k`.

**Comment by Ambrevar** [comment]
So what do you like better?

1.
```
"pt" 'org-agenda-set-tags
"pe" 'org-agenda-set-effort
"o" 'org-timer-set-timer
```

2.
```
"ct" 'org-agenda-set-tags
"ce" 'org-agenda-set-effort
"o" 'org-timer-set-timer
```

3.
```
"ct" 'org-agenda-set-tags
"ce" 'org-agenda-set-effort
"cT" 'org-timer-set-timer
```

4.
```
"ct" 'org-agenda-set-tags
"ce" 'org-agenda-set-effort
"cT" 'org-timer-set-timer
"ci" 'org-agenda-clock-in
"co" 'org-agenda-clock-out
```

**Comment by Ambrevar** [comment]
The call to arms: https://www.reddit.com/r/emacs/comments/7akqy3/evil_everywhere_the_rest_of_emacs/

**Comment by Somelauw** [comment]
>    Regular evil-org-mode binds org-agenda-todo-previousset, org-agenda-todo-nextset commands to C-S-h, C-S-l by the way and the other ones to just H and L.

> M-l and M-h are unused in Emacs mode and free in Evil mode, so why not just use them if we already use M-j and M-k.

1. They aren't consistent. In org-mode, *shift* is used for changing TODO state keyword and *meta* is used for promoting/demotion. Using *meta* for changing TODO state in org-agenda would be inconsistent.

2. It doesn't make sense to me to have a binding to org-agenda-todo-previousset but none to org-agenda-todo-previous-keyword. I am currently asking on the Emacs-orgmode mailing list why this would be. 

Since we already have a binding to `org-agenda-todo`, I think it's okay to not bind these functions. If you want to bind these anyway, `C-S-h` and `C-S-l` are the best keys in my opinion.

> So what do you like better?

```emacs-lisp
"ct" 'org-agenda-set-tags
"ce" 'org-agenda-set-effort
"cT" 'org-timer-set-timer
```

**Comment by Ambrevar** [comment]
1. It does not change TODO state, it changes the keyword set.  It's different.  But see next point.

2. I agree that ultimately upstream should be consistent with changing the TODO state.

> Since we already have a binding to org-agenda-todo, I think it's okay to not bind these functions. 

It's not the same thing.

**Comment by Somelauw** [comment]
Thanks. I'm okay with the current key bindings. Let me know when this can be merged.

> Unless we are missing something, this should probably be reported upstream.

I made a question on the mailing list.
https://lists.gnu.org/archive/html/emacs-orgmode/2017-11/msg00060.html

> 3 original bindings are not bound yet as I'm not sure of their use:
> 'org-agenda-date-prompt

It sometimes behaves as a combination of `org-agenda-schedule` and `org-agenda-deadline`. It changes the first timestamp inside a heading it can find.

> 'org-agenda-show-the-flagging-note

I asked on IRC and got directed to the following:
http://orgmode.org/manual/Pulling-from-MobileOrg.html#Pulling-from-MobileOrg
It's a bit niche. I don't have a strong opinion for a key binding. Maybe something uppercase.

> 'org-save-all-org-buffers ; Original binding "C-x C-s"
> Maybe it can be called on :w.

This might not be possible in a clean way. The closest I could find was https://stackoverflow.com/questions/12913713/rebinding-b-and-e-in-evil-normal-state-map.
Remapping `evil-write` is also a bad solution, because evil-write should be able to write your agenda to a custom file.

**Comment by Ambrevar** [comment]
I suggest we leave `C-x C-s` as it is for now.  It's not horrible, no need to try too hard :)
If an ideal solution pops up in the future, we can still add it.

What bindings do you suggest for 
- 'org-agenda-date-prompt`: `o`?  Random suggestion.
- `org-agenda-show-the-flagging-note`: what about `P`?

**Comment by Somelauw** [comment]
>    'org-agenda-date-prompt:o`? Random suggestion.
>    org-agenda-show-the-flagging-note: what about P?

I think we can go with these.

**Comment by Ambrevar** [comment]
Done.

**Comment by lbolla** [comment]
I'd love to have org-agenda support. Is this ready for merging?

**Comment by Somelauw** [comment]
@Ambrevar The issue above seems to be decided on `o` for sorting/ordering and `s` for searching/filtering. Do you think we can make that change and merge this?

**Comment by Ambrevar** [comment]
I suggest we wait for https://github.com/jojojames/evil-collection/pull/42 to be resolved.

**Comment by Ambrevar** [comment]
Done! I've also update a few other points to follow the rationale more closely.

**Comment by Somelauw** [comment]
Thanks. Do you want to update the descriptions of the `p`, `c`, `M-h`, `M-l` keys in the README.md? To solve the conflict in README.md, it would also be helpful to rebase your branch on HEAD.

**Comment by Ambrevar** [comment]
Done.  There were a few more bindings that were out of date.

**Comment by Somelauw** [comment]
Thanks for the good work. It has been merged.

**Pull request merged**
